customers/api/urls.py
from django.urls import path, include
from .views import CustomerSignUp, AddressInput, ChangePasswordView, ProfileUpdateView
app_name = 'customers_api'
urlpatterns = [
    path('signup', CustomerSignUp.as_view(), name='signUp'),
    path('address', AddressInput.as_view(), name=' address_input'),
    path('changepassword', ChangePasswordView.as_view(), name='change_password'),
    path('profile_update/', ProfileUpdateView.as_view(), name='profile_update'),
]

customers/urls.py
from django.urls import path
from .views import my_login, user_profile, my_logout, edit_profile, change_password_view
from product.views import products, filter_products

app_name = 'customers'
urlpatterns = [
    path('login/', my_login, name='login'),
    path('', products, name='index'),
    path('filter_category/<str:category>', filter_products, name='index'),
    path('profile/', user_profile, name='profile'),
    path('logout/', my_logout, name='log out'),
    path('edit-profile/', edit_profile, name='edit profile'),
    path('change_password/', change_password_view, name='change_password')
]

orders/urls.py
from django.urls import path
from .views import add_item_view, basket

app_name = 'orders'
urlpatterns = [
    path('basket/', basket, name='basket'),
    # path('basket/delete/', delete_item_from_basket, name='delete_item_from_basket'),
    # path('checkout/', checkout, name='checkout'),
    path('add_to_cart/<int:pk>', add_item_view, name='add_to_cart')
]

product/urls.py
from django.urls import path
from .views import product_add, c, product_history, product_detail, filter_products
from django.urls import path
# from orders.views import basket_view, delete_item_from_basket, checkout

app_name = 'product'

urlpatterns = [
    path('addproduct', product_add, name='productadd'),
    path('history', product_history),
    path('product_detials/<int:pk>', product_detail, name='product_detail'),
    path('categories/<str:category>', filter_products, name='categories'),
    # path('product_history', product_history, name='product_history'),
    path('c', c, name='c')
]

shop_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('core.api.urls')),
    path('', include('customers.urls', namespace='customers')),
    path('product/', include('product.urls',namespace='product')),
    path('order/', include('orders.urls')),
    path('password_reset/', include('django_rest_passwordreset.urls', namespace='password_reset')),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.dispatch import receiver
from django.urls import reverse
from django_rest_passwordreset.signals import reset_password_token_created
from django.core.mail import send_mail


class Customer(AbstractUser):
    email = models.EmailField()
    first_name = models.CharField(max_length=100, null=False)
    last_name = models.CharField(max_length=100, null=False)
    birthday = models.DateField(null=True, blank=True)
    ID_card_number = models.PositiveIntegerField(unique=True)
    date_entered = models.DateField(auto_now=True)
    mobile_number = models.CharField(max_length=11, unique=True)
    home_number = models.CharField(max_length=11)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


# going to be a form
class Address(models.Model):
    user = models.OneToOneField(Customer, on_delete=models.CASCADE)
    address_name = models.CharField(max_length=50)
    providence = models.CharField(max_length=16)
    # use library
    city = models.CharField(max_length=35)
    postal_code = models.PositiveSmallIntegerField()
    # address with choice must be added
    address_detail = models.TextField()

    def __str__(self):
        return f'{self.address_name}'


@receiver(reset_password_token_created)
def password_reset_token_created(sender, instance, reset_password_token, *args, **kwargs):
    email_plaintext_message = "{}?token={}".format(reverse('password_reset:reset-password-request'),
                                                   reset_password_token.key)

    send_mail(
        # title:
        "Password Reset for {title}".format(title="Some website title"),
        # message:
        email_plaintext_message,
        # from:
        "noreply@somehost.local",
        # to:
        [reset_password_token.user.email]
    )

customers/forms.py
from django import forms
from .models import Customer


class LoginForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['username', 'password']


class UserProfile(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['first_name', 'last_name', 'email', 'birthday', 'mobile_number', 'home_number']

customers/api/views.py
from django.shortcuts import get_object_or_404
from rest_framework import status
from rest_framework.generics import CreateAPIView, UpdateAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView
from customers.models import Customer

from .serializers import UserSerializer, AddressSerializer, ChangePasswordSerializer, ProfileUpdateSerializer


class CustomerSignUp(CreateAPIView):
    serializer_class = UserSerializer


class AddressInput(CreateAPIView):
    serializer_class = AddressSerializer


class ProfileUpdateView(CreateAPIView):
    serializer_class = ProfileUpdateSerializer


class ChangePasswordView(UpdateAPIView):
    serializer_class = ChangePasswordSerializer
    model = Customer
    permission_classes = (IsAuthenticated,)

    def get_object(self, queryset=None):
        obj = self.request.user
        return obj

    def update(self, request, *args, **kwargs):

        self.object = self.get_object()
        serializer = self.get_serializer(data=request.data)

        if serializer.is_valid():
            # Checking old password
            if not self.object.check_password(serializer.validated_data['password']):
                return Response({"password": ["Wrong password."]}, status=status.HTTP_400_BAD_REQUEST)

            # Checking new password length
            elif len(serializer.validated_data['new_password']) < 8:
                return Response({"new_password": ["Your password must be at least 8 characters long."]},
                                status=status.HTTP_400_BAD_REQUEST)
            # Checking new password and new password check

            elif serializer.validated_data['new_password'] != serializer.validated_data['new_password_check']:
                return Response({"passwords": ["New password and New password check must match."]},
                                status=status.HTTP_400_BAD_REQUEST)

            # If no error occurs, the password will be updated
            self.object.set_password(serializer.validated_data['new_password'])
            self.object.save()

            response = {
                'status': 'success',
                'code': status.HTTP_200_OK,
                'message': 'Password updated successfully',
                'data': []
            }

            return Response(response)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

customers/views.py
import requests
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from customers.forms import LoginForm, UserProfile
from .models import Customer


# Create your views here.


def my_logout(request):
    logout(request)
    return redirect('customers:login')


def my_login(request):
    form = LoginForm()
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('customers:index')
        else:
            return HttpResponse('invalid login')
    return render(request, 'customers/login.html', {'form': form})


@login_required()
def user_profile(request):
    profile = Customer.objects.filter(id=request.user.id)
    return render(request, 'customers/profile.html', context={'profile': profile})


def edit_profile(request):
    if request.method == 'POST':
        form = UserProfile(request.POST, instance=request.user)
        if form.is_valid:
            form.save()
            return redirect('profile')
    else:
        form = UserProfile(instance=request.user)
        return render(request, 'customers/profile-edit.html', {'form': form})


@login_required()
def change_password_view(request):
    r = requests.get('http://127.0.0.1:8000/api/v1/customers/signup ').json()
    print(r)
    return render(request, 'customers/change_password.html', {'content': r})

templates/customers/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>django shop</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }
        .search {
            margin: 0 auto;
        }



        html,
        body {
            background: #EEF0F6 !important;
        }

        .container {
            background: #fff;
            border-radius: 12px;
            margin: 2rem auto;
            padding: .5rem;
            box-shadow: 0 .125rem .25rem rgba(0, 0, 0, .075) !important;
        }

        svg {
            max-width: 20px;
            fill: #DBDBDB;
            margin-left: -2rem;
        }

        input {
            border: none;
            background: none;
            outline: none;
            width: 15rem;
            border-radius: 12px;
            padding: .4rem 1rem;
            background: #eef0f6;
        }

        input:focus {
            border: 1px solid #0056b3;
        }


        .row {
            width: 100%;
            justify-content: space-between;
        }

        .search {
            display: flex;
            margin-right: 1rem;
            border-radius: 12px;
            margin-left: 1rem;
            align-items: center;
        }


        header {
            margin-top: 2rem;
        }

        #main {
            margin: 2rem 0;
        }

        #main .container {
            padding: 3rem 0;
        }

        .container {
            max-width: 90%;
            margin: 0 auto;
            display: flex;
            justify-content: center;
        }

        .container a {
            margin: .5rem 1rem;
            transition: all .3s linear !important;
        }

        .container a:hover {
            text-decoration: none !important;
            opacity: .9;
        }

        /*.username-nav {*/
        /*    display: flex;*/
        /*    justify-content: space-between;*/
        /*    width: 100%;*/

    </style>
</head>

<body>
<header id="header">
    <div class="container">
        <div class="row">
            <div class="username-nav">
                <div>
                    {% if user.is_authenticated %}
                    <a class="username-nav" href="{% url 'customers:profile' %}">profile </a>
                </div>
            </div>
                <a href="{% url 'customers:index' %}"> home </a>
                <a href="{% url 'customers:log out' %}"> logout </a>
                {% else %}
                <a href="{% url 'customers:login' %}"> login </a>
                {% endif %}
            </div>

            <div class="search">
                <input type="text" placeholder="products search...">
                <?xml version="1.0" encoding="iso-8859-1"?>
                <!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
                <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg"
                     xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 511.999 511.999"
                     style="enable-background:new 0 0 511.999 511.999;" xml:space="preserve">
                        <g>
                            <g>
                                <path
                                        d="M225.773,0.616C101.283,0.616,0,101.622,0,225.773s101.284,225.157,225.773,225.157s225.774-101.006,225.774-225.157
			S350.263,0.616,225.773,0.616z M225.773,413.917c-104.084,0-188.761-84.406-188.761-188.145
			c0-103.745,84.677-188.145,188.761-188.145s188.761,84.4,188.761,188.145C414.535,329.511,329.858,413.917,225.773,413.917z"/>
                            </g>
                        </g>
                    <g>
                            <g>
                                <path d="M506.547,479.756L385.024,358.85c-7.248-7.205-18.963-7.174-26.174,0.068c-7.205,7.248-7.174,18.962,0.068,26.174
			l121.523,120.906c3.615,3.59,8.328,5.385,13.053,5.385c4.756,0,9.506-1.82,13.121-5.453
			C513.82,498.681,513.789,486.967,506.547,479.756z"/>
                            </g>
                        </g>
                    <g>
                        </g>
                    <g>
                        </g>
                    <g>
                        </g>
                    <g>
                        </g>
                    <g>
                        </g>
                    <g>
                        </g>
                    <g>
                        </g>
                    <g>
                        </g>
                    <g>
                        </g>
                    <g>
                        </g>
                    <g>
                        </g>
                    <g>
                        </g>
                    <g>
                        </g>
                    <g>
                        </g>
                    <g>
                        </g>
                    </svg>

            </div>
        </div>
    </div>
</header>
<section id="main">
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</section>

</body>

</html>

templates/customers/change_password.html
{% extends 'customers/base.html' %}
{% block content %}
    {{ content }}
{% endblock %}

templates/customers/index.html
{% extends 'customers/base.html' %}
{% block content %}
{% for p in product %}
<div class="container py-5">
    <div class="row text-center py-3">
        <div class="col-lg-6 m-auto">
            <div class="row">
                <div class="card h-100">
                    <table>
                        <tr>
                            <th>
                                <div class="card-body ">
                                    {% if p.image %}
                                    <img src="{{ p.image.url }}" class="card-img-top" alt="product image">
                                    {% endif %}
                                    <br>
                                    <a class="card-text" href="{% url 'product:product_detail' pk=p.id %}">name : {{
                                        p.name }}</a>
                                    <p class="card-text">price : {{ p.price }}</p>

                                    {% if p.price_discount %}
                                    <u class="card-text">price : {{ p.price }}</u>
                                    <p class="card-text">price discount : {{ p.price_discount }}</p>
                                    {% endif%}
                                    <p class="card-text">description : {{ p.description }}</p>
                                    <a class="card-text" href="{% url 'product:categories' category=p.category %}">
                                        category :{{ p.category }}</a>
                                    <a class="card-text" href="{% url 'product:product_detail' pk=p.id %}">
                                        <button class="btn btn-warning">مشاهده بیشتر</button>
                                    </a>

                                </div>
                            </th>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    {% endfor %}
    {% if product.has_previous %}
    <a href="{% url 'customers:index' %}?page={{product.previous_page_number}}" class="btn-block"> Previous Page</a>
    {% endif %}
    {% if product.has_next %}
    <a href="{% url 'customers:index' %}?page={{product.next_page_number}}" class="btn-block"> Next Page</a>
    {% endif %}
</div>
{% endblock %}

templates/customers/login.html
{% extends 'customers/base.html' %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="log in">
</form>
<a href="{% url 'password_reset:reset-password-request' %}">
    <button class="btn btn-primary btn-md my-0 p"> reset password</button>
</a>
<a href="{% url 'customers_api:signUp' %}">
    <button class="btn btn-primary btn-md my-0 p"> register</button>
</a>
{% endblock %}

templates/customers/profile-edit.html
{% extends 'customers/base.html' %}
{% block content %}
    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit" class=" btn btn-primary ">
    </form>
{% endblock %}

templates/customers/profile.html
{% extends 'customers/base.html' %}
{% block content %}
{% for p in profile %}
    <div>
        <p>first name : {{ p.first_name }}</p>
        <p>last name : {{ p.last_name }}</p>
        <p>email  : {{ p.email }}</p>
        <p>birthday  : {{ p.birthday }}</p>
        <p>ID card number : {{ p.ID_card_number }}</p>
        <p>home number : {{ p.home_number }}</p>
        <p>mobile number : {{ p.mobile_number }}</p>
        <p>date entered : {{ p.date_entered }}</p>
{#        <img src="{% url p.image %}" alt="profile image">#}
    </div>
    <hr>
    <div>
        <a href="{% url 'customers:edit profile' %}" ><button  class="btn btn-primary btn-md my-0 p">edit profile</button></a>
    </div>
        <br>
    <div>
        <a href="{% url 'customers_api:change_password' %}"><button  class="btn btn-primary btn-md my-0 p"> change password</button></a>
    </div>
{% endfor %}
    
{% endblock %}

templates/customers/reset_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>