orders/urls.py
from django.urls import path
from .views import add_item_view, basket

app_name = 'orders'
urlpatterns = [
    path('basket/', basket, name='basket'),
    # path('basket/delete/', delete_item_from_basket, name='delete_item_from_basket'),
    # path('checkout/', checkout, name='checkout'),
    path('add_to_cart/<int:pk>', add_item_view, name='add_to_cart')
]

product/urls.py
from django.urls import path
from .views import product_add, c, product_history, product_detail, filter_products
from django.urls import path
# from orders.views import basket_view, delete_item_from_basket, checkout

app_name = 'product'

urlpatterns = [
    path('addproduct', product_add, name='productadd'),
    path('history', product_history),
    path('product_detials/<int:pk>', product_detail, name='product_detail'),
    path('categories/<str:category>', filter_products, name='categories'),
    # path('product_history', product_history, name='product_history'),
    path('c', c, name='c')
]

shop_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('core.api.urls')),
    path('', include('customers.urls', namespace='customers')),
    path('product/', include('product.urls',namespace='product')),
    path('order/', include('orders.urls')),
    path('password_reset/', include('django_rest_passwordreset.urls', namespace='password_reset')),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=100)
    sub_category = models.ForeignKey('self',
                                     on_delete=models.CASCADE,
                                     blank=True,
                                     null=True)

    def __str__(self):
        return self.category_name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT, null=True)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    price = models.PositiveIntegerField()
    price_discount = models.PositiveIntegerField(null=True, blank=True)
    size_choices = (('extra small', 'extras small'), ('small', 'small'),
                    ('medium', 'medium'), ('large', 'large'), ('extra large',
                                                               'extra large'))
    size = models.CharField(max_length=30, choices=size_choices)
    color = models.CharField(max_length=25)
    unit_in_stock = models.PositiveIntegerField()
    ranking_choices = (
        ('Very Bad', 'Very Bad'),
        ('Bad', 'Bad'),
        ('Not Bad', 'Not Bad'),
        ('Good', 'Good'),
        ('Very Good', 'Very Good'),
    )
    ranking = models.CharField(max_length=30, choices=ranking_choices)
    image = models.ImageField(upload_to='media/product', blank=True, null=True)

    def __str__(self):
        return self.name


# class Discount(models.Model):
#     discount_code = models.PositiveIntegerField()
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#     amount = models.PositiveIntegerField()

#     def __str__(self):
#         return self.amount

product/forms.py
from django import forms
from .models import Product, Category


class ProductAdd(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'


class CategoryAdd(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

product/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Category, Product
from orders.models import Orders
from .forms import ProductAdd, CategoryAdd
from django.core.paginator import Paginator, EmptyPage


# Create your views here.


def products(request):
    product = Product.objects.all()
    p = Paginator(product, 2)
    page_num = request.GET.get('page', 1)
    try:
        page = p.page(page_num)
    except EmptyPage:
        page = p.page(1)
    return render(request, 'customers/index.html', {'product': page})


def filter_products(request, category):
    category_field = get_object_or_404(Category, category_name=category)
    product = Product.objects.filter(category=category_field)
    return render(request, 'customers/index.html', {'product': product})


def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {'product': product}
    return render(request, 'product/product_detail.html', context)


@login_required
def product_history(request):
    user = request.user
    last_items = Orders.objects.filter(customer=request.user).last()
    list_item = []
    if last_items:
        for item in last_items.order_detail.all().order_by('-pk')[:10]:
            list_item.append(item)

    else:
        return HttpResponse("You don't have orders yet!")

    template_name = 'product/history_order.html'
    context = {'items': list_item}
    return render(request, template_name, context)


def product_add(request):
    if request.method == 'POST':
        form = ProductAdd(request.POST, request.FILES)
        if form.is_valid:
            form.save()
            return HttpResponse('Ok!')
    else:
        form = ProductAdd()
        return render(request, 'product/productadd.html', {'form': form})


def c(request):
    if request.method == 'POST':
        form = CategoryAdd(request.POST)
        if form.is_valid:
            form.save()
            return HttpResponse('Ok!')
    else:
        form = CategoryAdd()
        return render(request, 'product/C.html', {'form': form})

# def Discount(request):
# pro

templates/product/c.html
{% extends 'customers/base.html' %}
{% block content %}
    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
    </form>
{% endblock %}

templates/product/history_order.html
{% extends 'customers/base.html' %}
{% block content %}
{% for item in items %}
            <p>{{ item.name }}</p>
            <p>{{item.price}}</p>
{% endfor %}

{% endblock %}

templates/product/index.html
{% extends 'customers/base.html' %}
{% block content %}
{% for p in product %}
<table>
    <tr>
        <th>
            <p>{{ p }}</p>
        </th>
    </tr>
</table>
{% endfor %}

{% endblock %}

templates/product/product_detail.html
{% extends 'customers/base.html' %}
{#{% for p in product %}#}
{% block content %}
<div class="container py-5">
    <div class="row text-center py-3">
        <div class="col-lg-6 m-auto">
            <div class="row">
                <div class="card h-100">
                    <table>
                        <tr>
                            <th>
                                <div class="card-body">
                                    {% if product.image %}
                                    <img src="{{ product.image.url }}" class="card-img-top" alt="product image">
                                    {% endif %}

                                    <p class="card-text">name : {{   product.name }}</p>
                                    <p class="card-text">price : {{ product.price }}</p>
                                    <p class="card-text">price discount : {{ product.price_discount }}</p>
                                    <p class="card-text">description : {{ product.description}}</p>
                                    <p class="card-text">ranking : {{ product.ranking}}</p>
                                    <p class="card-text">color : {{ product.color}}</p>

                                    {# <input type="button" value="افزودن به سبد خرید">#}
                                    <a href="{% url 'orders:add_to_cart' pk=product.id %}"
                                       class="btn btn-primary btn-md my-0 p">
                                        اضافه کردن به سبد خرید
                                    </a>
                                </div>
                            </th>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{#{% endfor %}#}
{% endblock %}

templates/product/productadd.html
{% extends 'customers/base.html' %}
{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="add product">
    </form>
{% endblock %}